include:
  - tests/compose.yml

services:
  # docker compose run --rm -i init [container_name]
  init:
    extends: &base
      file: docker/compose.yml
      service: base
    image: deanayalon/bind-init
    container_name: bind-initializer
    build: 
      dockerfile: docker/dockerfile
      tags: [ghcr.io/deanayalon/bind-init]
      platforms:
        - linux/amd64
        - linux/arm64/v8

  # docker compose --profile dev watch
  dev:
    extends: *base
    image: deanayalon/bind-init:${DEV_TAG:-dev}
    profiles: [dev]
    build: 
      dockerfile: docker/dev/dockerfile.${DEV_TAG:-dev}
    develop:
      watch:
        - path: main.py
          action: sync
          target: /app/main.py
        - path: docker/dev/dockerfile.${DEV_TAG:-dev}
          action: rebuild
        - path: pyproject.toml
          action: rebuild
    container_name: bind-init-dev${DEV_TAG:+-}$DEV_TAG
    entrypoint: tail
    command: -f /dev/null