include:
  - tests/compose.yml

services:
  # docker compose run --rm -i init [container_name]
  init:
    extends: &base
      file: docker/compose.yml
      service: base
    image: deanayalon/bind-init
    container_name: bind-initializer
    build: 
      dockerfile: docker/dockerfile
      tags: [ghcr.io/deanayalon/bind-init]
      platforms:
        - linux/amd64
        - linux/arm64/v8

  dev:
    extends: *base
    image: deanayalon/bind-init:dev
    build: 
      dockerfile: docker/dockerfile.dev
    develop:
      watch:
        - path: main.py
          action: sync
          target: /app/main.py
        - path: docker/dockerfile.dev
          action: rebuild
        - path: pyproject.toml
          action: rebuild
    container_name: bind-init-dev
    entrypoint: tail
    command: -f /dev/null