services:
  alpine:
    image: alpine
    profiles: [test]
    container_name: bind-test-alpine
    stop_grace_period: 0s
    volumes:
      - ./mnt/alpine/test:/media             # init should populate this with the default contents of alpine:/media
      - ./mnt/alpine/something:/something    # No default content
      - somevol:/somevol              # Named volume
    command: tail -f /dev/null

  # docker compose create binary
  binary:
    build:
      dockerfile_inline: |
        FROM hello-world
        COPY main.py test/main.py
    profiles: [test]
    container_name: bind-test-binary
    stop_grace_period: 0s
    volumes:
      - ./mnt/hello/mnt:/mnt
      - ./mnt/hello/test:/test

volumes:
  somevol: