FROM deanayalon/poetry AS deps

# Python dependencies
COPY pyproject.toml poetry.lock ./
RUN poetry install

FROM python:3.12-slim-bookworm

LABEL org.opencontainers.image.source https://github.com/deanayalon/docker-bind-init
LABEL org.opencontainers.image.authors Dean Ayalon - dev@deanayalon.com

WORKDIR /app
ENV PATH="/app/.venv/bin:$PATH"

COPY --from=docker:cli /usr/local/bin/docker /usr/local/bin/docker
RUN mkdir exports
COPY --from=deps /app/.venv ./.venv

COPY main.py .

ENTRYPOINT ["python3", "main.py"]